#!/usr/bin/env bash
set -e
export SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if [[ -n $1 ]]; then
	if [[ $1 == '--help' ]]; then
		printf "Run homeshick working copy interactively\n"
		printf " Usage: interactive [shell]\n"
		exit 0
	else
		if [[ $# > 1 ]]; then
			printf "only one SHELL argument allowed\n" >&2
			exit 64 # 64=$EX_USAGE
		fi
		_shell=$1
	fi
fi

if [[ -z $_shell ]]; then
	_shell=$SHELL
fi

source $SCRIPTDIR/helper.bash
export_env_vars
setup_env

setup_script="${SCRIPTDIR}/setup.sh"
if [[ -f $setup_script ]]; then
	$setup_script
fi

cd $HOME

exec /usr/bin/env $_shell
