#!/usr/bin/env bash

shopt -s extglob
shopt -s nullglob

shellcheck --shell=bash \
	bin/homeshick \
	lib/!(exit_status).sh \
	{,lib/commands/,test/,test/fixtures/}*.{sh,bash} \
	test/{run,interactive,shellcheck}
