#!/usr/bin/env bash

main() {
  cd "$(dirname "${BASH_SOURCE[0]}")/.." || return 1

  local ret=0
  shellcheck --source-path=SCRIPTDIR "$@" -- \
    homeshick.sh \
    bin/homeshick \
    lib/*.sh \
    lib/commands/*.sh \
    test/{run,interactive,shellcheck,*.sh} \
    test/fixtures/*.sh \
    test/suites/*.bats || ret=$?
  shellcheck --shell=sh homeshick.sh || ret=$?
  shellcheck --shell=bash homeshick.sh || ret=$?
  shellcheck --shell=dash homeshick.sh || ret=$?
  shellcheck --shell=ksh homeshick.sh || ret=$?
  return $ret
}
main "$@"
